#!/bin/bash
qflow synthesize rca_4bit
qflow synthesize rca_5bit
qflow synthesize rca_6bit
qflow synthesize rca_7bit
qflow synthesize rca_8bit
qflow synthesize rca_9bit
qflow synthesize rca_10bit
qflow synthesize rca_11bit
qflow synthesize rca_12bit
qflow synthesize rca_13bit
qflow synthesize rca_14bit
qflow synthesize rca_15bit
qflow synthesize rca_16bit
qflow synthesize rca_17bit
qflow synthesize rca_18bit
qflow synthesize rca_19bit
qflow synthesize rca_20bit
qflow synthesize rca_21bit
qflow synthesize rca_22bit
qflow synthesize rca_23bit
qflow synthesize rca_24bit
qflow synthesize rca_25bit
qflow synthesize rca_26bit
qflow synthesize rca_27bit
qflow synthesize rca_28bit
qflow synthesize rca_29bit
qflow synthesize rca_30bit
qflow synthesize rca_31bit
qflow synthesize rca_32bit
qflow synthesize rca_33bit
qflow synthesize rca_34bit
qflow synthesize rca_35bit
qflow synthesize rca_36bit
qflow synthesize rca_37bit
qflow synthesize rca_38bit
qflow synthesize rca_39bit
qflow synthesize rca_40bit
qflow synthesize rca_41bit
qflow synthesize rca_42bit
qflow synthesize rca_43bit
qflow synthesize rca_44bit
qflow synthesize rca_45bit
qflow synthesize rca_46bit
qflow synthesize rca_47bit
qflow synthesize rca_48bit
qflow synthesize rca_49bit
qflow synthesize rca_50bit
qflow synthesize rca_51bit
qflow synthesize rca_52bit
qflow synthesize rca_53bit
qflow synthesize rca_54bit
qflow synthesize rca_55bit
qflow synthesize rca_56bit
qflow synthesize rca_57bit
qflow synthesize rca_58bit
qflow synthesize rca_59bit
qflow synthesize rca_60bit
qflow synthesize rca_61bit
qflow synthesize rca_62bit
qflow synthesize rca_63bit
qflow synthesize rca_64bit
