#!/bin/bash
qflow synthesize cla_4bit
qflow synthesize cla_5bit
qflow synthesize cla_6bit
qflow synthesize cla_7bit
qflow synthesize cla_8bit
qflow synthesize cla_9bit
qflow synthesize cla_10bit
qflow synthesize cla_11bit
qflow synthesize cla_12bit
qflow synthesize cla_13bit
qflow synthesize cla_14bit
qflow synthesize cla_15bit
qflow synthesize cla_16bit
qflow synthesize cla_17bit
qflow synthesize cla_18bit
qflow synthesize cla_19bit
qflow synthesize cla_20bit
qflow synthesize cla_21bit
qflow synthesize cla_22bit
qflow synthesize cla_23bit
qflow synthesize cla_24bit
qflow synthesize cla_25bit
qflow synthesize cla_26bit
qflow synthesize cla_27bit
qflow synthesize cla_28bit
qflow synthesize cla_29bit
qflow synthesize cla_30bit
qflow synthesize cla_31bit
qflow synthesize cla_32bit
qflow synthesize cla_33bit
qflow synthesize cla_34bit
qflow synthesize cla_35bit
qflow synthesize cla_36bit
qflow synthesize cla_37bit
qflow synthesize cla_38bit
qflow synthesize cla_39bit
qflow synthesize cla_40bit
qflow synthesize cla_41bit
qflow synthesize cla_42bit
qflow synthesize cla_43bit
qflow synthesize cla_44bit
qflow synthesize cla_45bit
qflow synthesize cla_46bit
qflow synthesize cla_47bit
qflow synthesize cla_48bit
qflow synthesize cla_49bit
qflow synthesize cla_50bit
qflow synthesize cla_51bit
qflow synthesize cla_52bit
qflow synthesize cla_53bit
qflow synthesize cla_54bit
qflow synthesize cla_55bit
qflow synthesize cla_56bit
qflow synthesize cla_57bit
qflow synthesize cla_58bit
qflow synthesize cla_59bit
qflow synthesize cla_60bit
qflow synthesize cla_61bit
qflow synthesize cla_62bit
qflow synthesize cla_63bit
qflow synthesize cla_64bit
