/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_12bit.v:3" *)
module rca_12bit(i_add_term1, i_add_term2, o_result);
  wire [12:0] _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _8_;
  wire _9_;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_12bit.v:6" *)
  input [11:0] i_add_term1;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_12bit.v:7" *)
  input [11:0] i_add_term2;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_12bit.v:8" *)
  output [12:0] o_result;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_12bit.v:11" *)
  wire [12:0] w_CARRY;
  NAND2X1 _100_ (
    .A(i_add_term2[4]),
    .B(i_add_term1[4]),
    .Y(_6_)
  );
  NAND3X1 _101_ (
    .A(_4_),
    .B(_6_),
    .C(_5_),
    .Y(_7_)
  );
  NOR2X1 _102_ (
    .A(i_add_term2[4]),
    .B(i_add_term1[4]),
    .Y(_1_)
  );
  AND2X2 _103_ (
    .A(i_add_term2[4]),
    .B(i_add_term1[4]),
    .Y(_2_)
  );
  OAI21X1 _104_ (
    .A(_1_),
    .B(_2_),
    .C(w_CARRY[4]),
    .Y(_3_)
  );
  NAND2X1 _105_ (
    .A(_3_),
    .B(_7_),
    .Y(_0_[4])
  );
  OAI21X1 _106_ (
    .A(_4_),
    .B(_1_),
    .C(_6_),
    .Y(w_CARRY[5])
  );
  INVX1 _107_ (
    .A(w_CARRY[5]),
    .Y(_11_)
  );
  OR2X2 _108_ (
    .A(i_add_term2[5]),
    .B(i_add_term1[5]),
    .Y(_12_)
  );
  NAND2X1 _109_ (
    .A(i_add_term2[5]),
    .B(i_add_term1[5]),
    .Y(_13_)
  );
  NAND3X1 _110_ (
    .A(_11_),
    .B(_13_),
    .C(_12_),
    .Y(_14_)
  );
  NOR2X1 _111_ (
    .A(i_add_term2[5]),
    .B(i_add_term1[5]),
    .Y(_8_)
  );
  AND2X2 _112_ (
    .A(i_add_term2[5]),
    .B(i_add_term1[5]),
    .Y(_9_)
  );
  OAI21X1 _113_ (
    .A(_8_),
    .B(_9_),
    .C(w_CARRY[5]),
    .Y(_10_)
  );
  NAND2X1 _114_ (
    .A(_10_),
    .B(_14_),
    .Y(_0_[5])
  );
  OAI21X1 _115_ (
    .A(_11_),
    .B(_8_),
    .C(_13_),
    .Y(w_CARRY[6])
  );
  INVX1 _116_ (
    .A(w_CARRY[6]),
    .Y(_18_)
  );
  OR2X2 _117_ (
    .A(i_add_term2[6]),
    .B(i_add_term1[6]),
    .Y(_19_)
  );
  NAND2X1 _118_ (
    .A(i_add_term2[6]),
    .B(i_add_term1[6]),
    .Y(_20_)
  );
  NAND3X1 _119_ (
    .A(_18_),
    .B(_20_),
    .C(_19_),
    .Y(_21_)
  );
  NOR2X1 _120_ (
    .A(i_add_term2[6]),
    .B(i_add_term1[6]),
    .Y(_15_)
  );
  AND2X2 _121_ (
    .A(i_add_term2[6]),
    .B(i_add_term1[6]),
    .Y(_16_)
  );
  OAI21X1 _122_ (
    .A(_15_),
    .B(_16_),
    .C(w_CARRY[6]),
    .Y(_17_)
  );
  NAND2X1 _123_ (
    .A(_17_),
    .B(_21_),
    .Y(_0_[6])
  );
  OAI21X1 _124_ (
    .A(_18_),
    .B(_15_),
    .C(_20_),
    .Y(w_CARRY[7])
  );
  INVX1 _125_ (
    .A(w_CARRY[7]),
    .Y(_25_)
  );
  OR2X2 _126_ (
    .A(i_add_term2[7]),
    .B(i_add_term1[7]),
    .Y(_26_)
  );
  NAND2X1 _127_ (
    .A(i_add_term2[7]),
    .B(i_add_term1[7]),
    .Y(_27_)
  );
  NAND3X1 _128_ (
    .A(_25_),
    .B(_27_),
    .C(_26_),
    .Y(_28_)
  );
  NOR2X1 _129_ (
    .A(i_add_term2[7]),
    .B(i_add_term1[7]),
    .Y(_22_)
  );
  AND2X2 _130_ (
    .A(i_add_term2[7]),
    .B(i_add_term1[7]),
    .Y(_23_)
  );
  OAI21X1 _131_ (
    .A(_22_),
    .B(_23_),
    .C(w_CARRY[7]),
    .Y(_24_)
  );
  NAND2X1 _132_ (
    .A(_24_),
    .B(_28_),
    .Y(_0_[7])
  );
  OAI21X1 _133_ (
    .A(_25_),
    .B(_22_),
    .C(_27_),
    .Y(w_CARRY[8])
  );
  INVX1 _134_ (
    .A(w_CARRY[8]),
    .Y(_32_)
  );
  OR2X2 _135_ (
    .A(i_add_term2[8]),
    .B(i_add_term1[8]),
    .Y(_33_)
  );
  NAND2X1 _136_ (
    .A(i_add_term2[8]),
    .B(i_add_term1[8]),
    .Y(_34_)
  );
  NAND3X1 _137_ (
    .A(_32_),
    .B(_34_),
    .C(_33_),
    .Y(_35_)
  );
  NOR2X1 _138_ (
    .A(i_add_term2[8]),
    .B(i_add_term1[8]),
    .Y(_29_)
  );
  AND2X2 _139_ (
    .A(i_add_term2[8]),
    .B(i_add_term1[8]),
    .Y(_30_)
  );
  OAI21X1 _140_ (
    .A(_29_),
    .B(_30_),
    .C(w_CARRY[8]),
    .Y(_31_)
  );
  NAND2X1 _141_ (
    .A(_31_),
    .B(_35_),
    .Y(_0_[8])
  );
  OAI21X1 _142_ (
    .A(_32_),
    .B(_29_),
    .C(_34_),
    .Y(w_CARRY[9])
  );
  INVX1 _143_ (
    .A(w_CARRY[9]),
    .Y(_39_)
  );
  OR2X2 _144_ (
    .A(i_add_term2[9]),
    .B(i_add_term1[9]),
    .Y(_40_)
  );
  NAND2X1 _145_ (
    .A(i_add_term2[9]),
    .B(i_add_term1[9]),
    .Y(_41_)
  );
  NAND3X1 _146_ (
    .A(_39_),
    .B(_41_),
    .C(_40_),
    .Y(_42_)
  );
  NOR2X1 _147_ (
    .A(i_add_term2[9]),
    .B(i_add_term1[9]),
    .Y(_36_)
  );
  AND2X2 _148_ (
    .A(i_add_term2[9]),
    .B(i_add_term1[9]),
    .Y(_37_)
  );
  OAI21X1 _149_ (
    .A(_36_),
    .B(_37_),
    .C(w_CARRY[9]),
    .Y(_38_)
  );
  NAND2X1 _150_ (
    .A(_38_),
    .B(_42_),
    .Y(_0_[9])
  );
  OAI21X1 _151_ (
    .A(_39_),
    .B(_36_),
    .C(_41_),
    .Y(w_CARRY[10])
  );
  INVX1 _152_ (
    .A(w_CARRY[10]),
    .Y(_46_)
  );
  OR2X2 _153_ (
    .A(i_add_term2[10]),
    .B(i_add_term1[10]),
    .Y(_47_)
  );
  NAND2X1 _154_ (
    .A(i_add_term2[10]),
    .B(i_add_term1[10]),
    .Y(_48_)
  );
  NAND3X1 _155_ (
    .A(_46_),
    .B(_48_),
    .C(_47_),
    .Y(_49_)
  );
  NOR2X1 _156_ (
    .A(i_add_term2[10]),
    .B(i_add_term1[10]),
    .Y(_43_)
  );
  AND2X2 _157_ (
    .A(i_add_term2[10]),
    .B(i_add_term1[10]),
    .Y(_44_)
  );
  OAI21X1 _158_ (
    .A(_43_),
    .B(_44_),
    .C(w_CARRY[10]),
    .Y(_45_)
  );
  NAND2X1 _159_ (
    .A(_45_),
    .B(_49_),
    .Y(_0_[10])
  );
  OAI21X1 _160_ (
    .A(_46_),
    .B(_43_),
    .C(_48_),
    .Y(w_CARRY[11])
  );
  INVX1 _161_ (
    .A(w_CARRY[11]),
    .Y(_53_)
  );
  OR2X2 _162_ (
    .A(i_add_term2[11]),
    .B(i_add_term1[11]),
    .Y(_54_)
  );
  NAND2X1 _163_ (
    .A(i_add_term2[11]),
    .B(i_add_term1[11]),
    .Y(_55_)
  );
  NAND3X1 _164_ (
    .A(_53_),
    .B(_55_),
    .C(_54_),
    .Y(_56_)
  );
  NOR2X1 _165_ (
    .A(i_add_term2[11]),
    .B(i_add_term1[11]),
    .Y(_50_)
  );
  AND2X2 _166_ (
    .A(i_add_term2[11]),
    .B(i_add_term1[11]),
    .Y(_51_)
  );
  OAI21X1 _167_ (
    .A(_50_),
    .B(_51_),
    .C(w_CARRY[11]),
    .Y(_52_)
  );
  NAND2X1 _168_ (
    .A(_52_),
    .B(_56_),
    .Y(_0_[11])
  );
  OAI21X1 _169_ (
    .A(_53_),
    .B(_50_),
    .C(_55_),
    .Y(w_CARRY[12])
  );
  INVX1 _170_ (
    .A(1'h0),
    .Y(_60_)
  );
  OR2X2 _171_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_61_)
  );
  NAND2X1 _172_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_62_)
  );
  NAND3X1 _173_ (
    .A(_60_),
    .B(_62_),
    .C(_61_),
    .Y(_63_)
  );
  NOR2X1 _174_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_57_)
  );
  AND2X2 _175_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_58_)
  );
  OAI21X1 _176_ (
    .A(_57_),
    .B(_58_),
    .C(1'h0),
    .Y(_59_)
  );
  NAND2X1 _177_ (
    .A(_59_),
    .B(_63_),
    .Y(_0_[0])
  );
  OAI21X1 _178_ (
    .A(_60_),
    .B(_57_),
    .C(_62_),
    .Y(w_CARRY[1])
  );
  INVX1 _179_ (
    .A(w_CARRY[1]),
    .Y(_67_)
  );
  OR2X2 _180_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_68_)
  );
  NAND2X1 _181_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_69_)
  );
  NAND3X1 _182_ (
    .A(_67_),
    .B(_69_),
    .C(_68_),
    .Y(_70_)
  );
  NOR2X1 _183_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_64_)
  );
  AND2X2 _184_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_65_)
  );
  OAI21X1 _185_ (
    .A(_64_),
    .B(_65_),
    .C(w_CARRY[1]),
    .Y(_66_)
  );
  NAND2X1 _186_ (
    .A(_66_),
    .B(_70_),
    .Y(_0_[1])
  );
  OAI21X1 _187_ (
    .A(_67_),
    .B(_64_),
    .C(_69_),
    .Y(w_CARRY[2])
  );
  INVX1 _188_ (
    .A(w_CARRY[2]),
    .Y(_74_)
  );
  OR2X2 _189_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_75_)
  );
  NAND2X1 _190_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_76_)
  );
  NAND3X1 _191_ (
    .A(_74_),
    .B(_76_),
    .C(_75_),
    .Y(_77_)
  );
  NOR2X1 _192_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_71_)
  );
  AND2X2 _193_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_72_)
  );
  OAI21X1 _194_ (
    .A(_71_),
    .B(_72_),
    .C(w_CARRY[2]),
    .Y(_73_)
  );
  NAND2X1 _195_ (
    .A(_73_),
    .B(_77_),
    .Y(_0_[2])
  );
  OAI21X1 _196_ (
    .A(_74_),
    .B(_71_),
    .C(_76_),
    .Y(w_CARRY[3])
  );
  INVX1 _197_ (
    .A(w_CARRY[3]),
    .Y(_81_)
  );
  OR2X2 _198_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_82_)
  );
  NAND2X1 _199_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_83_)
  );
  NAND3X1 _200_ (
    .A(_81_),
    .B(_83_),
    .C(_82_),
    .Y(_84_)
  );
  NOR2X1 _201_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_78_)
  );
  AND2X2 _202_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_79_)
  );
  OAI21X1 _203_ (
    .A(_78_),
    .B(_79_),
    .C(w_CARRY[3]),
    .Y(_80_)
  );
  NAND2X1 _204_ (
    .A(_80_),
    .B(_84_),
    .Y(_0_[3])
  );
  OAI21X1 _205_ (
    .A(_81_),
    .B(_78_),
    .C(_83_),
    .Y(w_CARRY[4])
  );
  (* keep = 32'd1 *)
  BUFX2 _85_ (
    .A(_0_[0]),
    .Y(o_result[0])
  );
  (* keep = 32'd1 *)
  BUFX2 _86_ (
    .A(_0_[1]),
    .Y(o_result[1])
  );
  (* keep = 32'd1 *)
  BUFX2 _87_ (
    .A(_0_[2]),
    .Y(o_result[2])
  );
  (* keep = 32'd1 *)
  BUFX2 _88_ (
    .A(_0_[3]),
    .Y(o_result[3])
  );
  (* keep = 32'd1 *)
  BUFX2 _89_ (
    .A(_0_[4]),
    .Y(o_result[4])
  );
  (* keep = 32'd1 *)
  BUFX2 _90_ (
    .A(_0_[5]),
    .Y(o_result[5])
  );
  (* keep = 32'd1 *)
  BUFX2 _91_ (
    .A(_0_[6]),
    .Y(o_result[6])
  );
  (* keep = 32'd1 *)
  BUFX2 _92_ (
    .A(_0_[7]),
    .Y(o_result[7])
  );
  (* keep = 32'd1 *)
  BUFX2 _93_ (
    .A(_0_[8]),
    .Y(o_result[8])
  );
  (* keep = 32'd1 *)
  BUFX2 _94_ (
    .A(_0_[9]),
    .Y(o_result[9])
  );
  (* keep = 32'd1 *)
  BUFX2 _95_ (
    .A(_0_[10]),
    .Y(o_result[10])
  );
  (* keep = 32'd1 *)
  BUFX2 _96_ (
    .A(_0_[11]),
    .Y(o_result[11])
  );
  (* keep = 32'd1 *)
  BUFX2 _97_ (
    .A(w_CARRY[12]),
    .Y(o_result[12])
  );
  INVX1 _98_ (
    .A(w_CARRY[4]),
    .Y(_4_)
  );
  OR2X2 _99_ (
    .A(i_add_term2[4]),
    .B(i_add_term1[4]),
    .Y(_5_)
  );
  assign _0_[12] = w_CARRY[12];
  assign w_CARRY[0] = 1'h0;
endmodule
