/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_4bit.v:3" *)
module rca_4bit(i_add_term1, i_add_term2, o_result);
  wire [4:0] _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_4bit.v:6" *)
  input [3:0] i_add_term1;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_4bit.v:7" *)
  input [3:0] i_add_term2;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_4bit.v:8" *)
  output [4:0] o_result;
  (* src = "/hdd/xuenong/Adder_Classification/source_new/testBatchAdderGenerator_rca/source/rca_4bit.v:11" *)
  wire [4:0] w_CARRY;
  (* keep = 32'd1 *)
  BUFX2 _29_ (
    .A(_0_[0]),
    .Y(o_result[0])
  );
  (* keep = 32'd1 *)
  BUFX2 _30_ (
    .A(_0_[1]),
    .Y(o_result[1])
  );
  (* keep = 32'd1 *)
  BUFX2 _31_ (
    .A(_0_[2]),
    .Y(o_result[2])
  );
  (* keep = 32'd1 *)
  BUFX2 _32_ (
    .A(_0_[3]),
    .Y(o_result[3])
  );
  (* keep = 32'd1 *)
  BUFX2 _33_ (
    .A(w_CARRY[4]),
    .Y(o_result[4])
  );
  INVX1 _34_ (
    .A(1'h0),
    .Y(_4_)
  );
  OR2X2 _35_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_5_)
  );
  NAND2X1 _36_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_6_)
  );
  NAND3X1 _37_ (
    .A(_4_),
    .B(_6_),
    .C(_5_),
    .Y(_7_)
  );
  NOR2X1 _38_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_1_)
  );
  AND2X2 _39_ (
    .A(i_add_term2[0]),
    .B(i_add_term1[0]),
    .Y(_2_)
  );
  OAI21X1 _40_ (
    .A(_1_),
    .B(_2_),
    .C(1'h0),
    .Y(_3_)
  );
  NAND2X1 _41_ (
    .A(_3_),
    .B(_7_),
    .Y(_0_[0])
  );
  OAI21X1 _42_ (
    .A(_4_),
    .B(_1_),
    .C(_6_),
    .Y(w_CARRY[1])
  );
  INVX1 _43_ (
    .A(w_CARRY[1]),
    .Y(_11_)
  );
  OR2X2 _44_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_12_)
  );
  NAND2X1 _45_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_13_)
  );
  NAND3X1 _46_ (
    .A(_11_),
    .B(_13_),
    .C(_12_),
    .Y(_14_)
  );
  NOR2X1 _47_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_8_)
  );
  AND2X2 _48_ (
    .A(i_add_term2[1]),
    .B(i_add_term1[1]),
    .Y(_9_)
  );
  OAI21X1 _49_ (
    .A(_8_),
    .B(_9_),
    .C(w_CARRY[1]),
    .Y(_10_)
  );
  NAND2X1 _50_ (
    .A(_10_),
    .B(_14_),
    .Y(_0_[1])
  );
  OAI21X1 _51_ (
    .A(_11_),
    .B(_8_),
    .C(_13_),
    .Y(w_CARRY[2])
  );
  INVX1 _52_ (
    .A(w_CARRY[2]),
    .Y(_18_)
  );
  OR2X2 _53_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_19_)
  );
  NAND2X1 _54_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_20_)
  );
  NAND3X1 _55_ (
    .A(_18_),
    .B(_20_),
    .C(_19_),
    .Y(_21_)
  );
  NOR2X1 _56_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_15_)
  );
  AND2X2 _57_ (
    .A(i_add_term2[2]),
    .B(i_add_term1[2]),
    .Y(_16_)
  );
  OAI21X1 _58_ (
    .A(_15_),
    .B(_16_),
    .C(w_CARRY[2]),
    .Y(_17_)
  );
  NAND2X1 _59_ (
    .A(_17_),
    .B(_21_),
    .Y(_0_[2])
  );
  OAI21X1 _60_ (
    .A(_18_),
    .B(_15_),
    .C(_20_),
    .Y(w_CARRY[3])
  );
  INVX1 _61_ (
    .A(w_CARRY[3]),
    .Y(_25_)
  );
  OR2X2 _62_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_26_)
  );
  NAND2X1 _63_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_27_)
  );
  NAND3X1 _64_ (
    .A(_25_),
    .B(_27_),
    .C(_26_),
    .Y(_28_)
  );
  NOR2X1 _65_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_22_)
  );
  AND2X2 _66_ (
    .A(i_add_term2[3]),
    .B(i_add_term1[3]),
    .Y(_23_)
  );
  OAI21X1 _67_ (
    .A(_22_),
    .B(_23_),
    .C(w_CARRY[3]),
    .Y(_24_)
  );
  NAND2X1 _68_ (
    .A(_24_),
    .B(_28_),
    .Y(_0_[3])
  );
  OAI21X1 _69_ (
    .A(_25_),
    .B(_22_),
    .C(_27_),
    .Y(w_CARRY[4])
  );
  assign _0_[4] = w_CARRY[4];
  assign w_CARRY[0] = 1'h0;
endmodule
