#!/bin/bash
qflow synthesize csa_4bit
qflow synthesize csa_5bit
qflow synthesize csa_6bit
qflow synthesize csa_7bit
qflow synthesize csa_8bit
qflow synthesize csa_9bit
qflow synthesize csa_10bit
qflow synthesize csa_11bit
qflow synthesize csa_12bit
qflow synthesize csa_13bit
qflow synthesize csa_14bit
qflow synthesize csa_15bit
qflow synthesize csa_16bit
qflow synthesize csa_17bit
qflow synthesize csa_18bit
qflow synthesize csa_19bit
qflow synthesize csa_20bit
qflow synthesize csa_21bit
qflow synthesize csa_22bit
qflow synthesize csa_23bit
qflow synthesize csa_24bit
qflow synthesize csa_25bit
qflow synthesize csa_26bit
qflow synthesize csa_27bit
qflow synthesize csa_28bit
qflow synthesize csa_29bit
qflow synthesize csa_30bit
qflow synthesize csa_31bit
qflow synthesize csa_32bit
qflow synthesize csa_33bit
qflow synthesize csa_34bit
qflow synthesize csa_35bit
qflow synthesize csa_36bit
qflow synthesize csa_37bit
qflow synthesize csa_38bit
qflow synthesize csa_39bit
qflow synthesize csa_40bit
qflow synthesize csa_41bit
qflow synthesize csa_42bit
qflow synthesize csa_43bit
qflow synthesize csa_44bit
qflow synthesize csa_45bit
qflow synthesize csa_46bit
qflow synthesize csa_47bit
qflow synthesize csa_48bit
qflow synthesize csa_49bit
qflow synthesize csa_50bit
qflow synthesize csa_51bit
qflow synthesize csa_52bit
qflow synthesize csa_53bit
qflow synthesize csa_54bit
qflow synthesize csa_55bit
qflow synthesize csa_56bit
qflow synthesize csa_57bit
qflow synthesize csa_58bit
qflow synthesize csa_59bit
qflow synthesize csa_60bit
qflow synthesize csa_61bit
qflow synthesize csa_62bit
qflow synthesize csa_63bit
qflow synthesize csa_64bit
